export const NAV_LINKS = [
  {
    code: 'discover',
    href: '/explore',
  },
  {
    code: 'submit',
    href: '/submit',
  },
  {
    code: 'startup',
    href: '/startup',
  },
];

export const RevalidateOneHour = 3600;
export const RevalidateOneDay = 3600 * 24;
export const RevalidateOneWeek = 3600 * 24 * 7;
export const RevalidateOneMonth = 3600 * 24 * 30;

export const PAGE_SIZE = 20;
export const InfoPageSize = 12;

export const FORM_PLACEHOLDER = 'https://tap4.ai/';

export const WEBSITE_EXAMPLE =
  '<a href="https://tap4.ai/" title="Tap4 AI Tools Directory">Tap4 AI Tools Diresctory</a>';

export const STARTUP_LIST = [
  {
    DA: 94,
    Website: 'Trustpilot',
    URL: 'http://trustpilot.com/',
    Price: 'Free',
    Tag: '',
  },
  {
    DA: 91,
    Website: 'ProductHunt',
    URL: 'https://www.producthunt.com/',
    Price: 'Free',
    Tag: '',
  },
  {
    DA: 90,
    Website: 'Capterra.com',
    URL: 'https://www.capterra.com/',
    Price: 'Free',
    Tag: '',
  },
  {
    DA: 86,
    Website: 'CB Insights',
    URL: 'https://www.cbinsights.com/',
    Price: 'Free',
    Tag: '',
  },
  {
    DA: 85,
    Website: 'Goodfirms',
    URL: 'https://www.goodfirms.co/',
    Price: 'Free',
    Tag: '',
  },
  {
    DA: 84,
    Website: 'Devpost',
    URL: 'https://devpost.com/software',
    Price: 'Free',
    Tag: 'DevTools, Code projects',
  },
  {
    DA: 83,
    Website: 'Trustradius.com',
    URL: 'https://www.trustradius.com/',
    Price: 'Free',
    Tag: '',
  },
  {
    DA: 79,
    Website: 'Alternativeto',
    URL: 'http://alternativeto.net/',
    Price: 'Free',
    Tag: '',
  },
  {
    DA: 76,
    Website: 'EU startups',
    URL: 'https://www.eu-startups.com/',
    Price: 'Free',
    Tag: '',
  },
  {
    DA: 75,
    Website: 'Starterstory.com',
    URL: 'https://www.starterstory.com/',
    Price: 'Free',
    Tag: '',
  },
  {
    DA: 73,
    Website: 'Alternative',
    URL: 'https://alternative.me/',
    Price: 'Free',
    Tag: '',
  },
  {
    DA: 73,
    Website: 'Betalist',
    URL: 'https://betalist.com/',
    Price: 'Free',
    Tag: '',
  },
  {
    DA: 72,
    Website: 'Feedough',
    URL: 'https://www.feedough.com/',
    Price: 'Free',
    Tag: '',
  },
  {
    DA: 71,
    Website: 'CrowdReviews',
    URL: 'http://crowdreviews.com/',
    Price: 'Free',
    Tag: '',
  },
  {
    DA: 69,
    Website: "There's An AI For That",
    URL: 'https://theresanaiforthat.com/',
    Price: 'Free',
    Tag: '',
  },
  {
    DA: 69,
    Website: 'Saashub.com',
    URL: 'https://saashub.com/',
    Price: 'Free',
    Tag: '',
  },
  {
    DA: 66,
    Website: 'Startupranking',
    URL: 'https://startupranking.com/',
    Price: 'Free',
    Tag: '',
  },
  {
    DA: 64,
    Website: 'Startupstash.com',
    URL: 'https://startupstash.com/',
    Price: 'Free',
    Tag: '',
  },
  {
    DA: 62,
    Website: 'Pitchwall',
    URL: 'http://pitchwall.co/',
    Price: 'Free',
    Tag: '',
  },
  {
    DA: 57,
    Website: 'Toolify',
    URL: 'http://www.toolify.ai/',
    Price: 'Free',
    Tag: '',
  },
  {
    DA: 56,
    Website: 'Saasaitools',
    URL: 'https://saasaitools.com/',
    Price: 'Free',
    Tag: '',
  },
  {
    DA: 54,
    Website: 'TopAI.tools',
    URL: 'https://topai.tools/',
    Price: '$35.00',
    Tag: '',
  },
  {
    DA: 53,
    Website: 'VentureRadar',
    URL: 'https://www.ventureradar.com/database',
    Price: 'Free',
    Tag: '',
  },
  {
    DA: 53,
    Website: 'AIToolGuru',
    URL: 'https://aitoolguru.com/',
    Price: 'Free',
    Tag: 'AI',
  },
  {
    DA: 52,
    Website: 'Betabound',
    URL: 'https://betabound.com/',
    Price: 'Free',
    Tag: '',
  },
  {
    DA: 50,
    Website: 'Tooldirectory.AI',
    URL: 'http://tooldirectory.ai/',
    Price: '$10.00',
    Tag: '',
  },
  {
    DA: 50,
    Website: 'Future Tools',
    URL: 'https://www.futuretools.io/',
    Price: 'Free',
    Tag: '',
  },
  {
    DA: 44,
    Website: 'AI Scout',
    URL: 'http://aiscout.net/',
    Price: '$49.00',
    Tag: '',
  },
  {
    DA: 44,
    Website: 'Aitoptools',
    URL: 'https://aitoptools.com/',
    Price: '$99.00',
    Tag: '',
  },
  {
    DA: 44,
    Website: 'StartupBuffer',
    URL: 'https://startupbuffer.com/',
    Price: 'Free',
    Tag: 'All Startups',
  },
  {
    DA: 41,
    Website: 'Insider',
    URL: 'https://www.insidr.ai/submit-tools/',
    Price: 'Free',
    Tag: '',
  },
  {
    DA: 40,
    Website: 'SaaSWorthy',
    URL: 'https://www.saasworthy.com/',
    Price: 'Free',
    Tag: 'SaaS, All Startups',
  },
  {
    DA: 39,
    Website: 'Foundr AI',
    URL: 'https://foundr.ai/',
    Price: 'Free',
    Tag: '',
  },
  {
    DA: 38,
    Website: 'SoftwareWorld',
    URL: 'https://www.softwareworld.co/',
    Price: 'Free',
    Tag: 'All Startups',
  },
  {
    DA: 38,
    Website: 'LaunchingNext',
    URL: 'https://www.launchingnext.com/',
    Price: 'Free',
    Tag: 'All Startups',
  },
  {
    DA: 37,
    Website: 'TheRundown',
    URL: 'https://www.therundown.ai/',
    Price: 'Free',
    Tag: '',
  },
  {
    DA: 37,
    Website: 'AIToolSet',
    URL: 'https://www.aitoolset.com/',
    Price: 'Free',
    Tag: '',
  },
  {
    DA: 36,
    Website: 'Airt',
    URL: 'https://airt.ai/',
    Price: '$199',
    Tag: '',
  },
  {
    DA: 34,
    Website: 'AIToolsKit',
    URL: 'https://aitoolskit.ai/submit-ai-tool/',
    Price: 'Free',
    Tag: '',
  },
  {
    DA: 38,
    Website: 'Tap4 AI',
    URL: 'https://tap4.ai/submit',
    Price: 'Free',
    Tag: 'AI',
  },
  {
    DA: 38,
    Website: 'TopFree AI',
    URL: 'https://topfree.ai/submit/',
    Price: 'Free',
    Tag: 'AI',
  },
  {
    DA: 34,
    Website: 'AITools.fyi',
    URL: 'https://www.aitools.fyi/',
    Price: '$10.00',
    Tag: '',
  },
  {
    DA: 34,
    Website: 'G2',
    URL: 'https://www.g2.com/',
    Price: 'Free',
    Tag: '',
  },
  {
    DA: 33,
    Website: 'Betapage',
    URL: 'https://betapage.co/',
    Price: 'Free',
    Tag: '',
  },
  {
    DA: 32,
    Website: 'AI Navigator',
    URL: 'http://ainav.substack.com/',
    Price: '$149',
    Tag: '',
  },
  {
    DA: 32,
    Website: 'MachineLearningMastery',
    URL: 'https://machinelearningmastery.com/',
    Price: 'Free',
    Tag: '',
  },
  {
    DA: 30,
    Website: 'EpicAI.tools',
    URL: 'https://epicai.tools/',
    Price: 'Free',
    Tag: '',
  },
  {
    DA: 29,
    Website: 'AiMondo',
    URL: 'https://aimondo.ai/',
    Price: 'Free',
    Tag: '',
  },
  {
    DA: 28,
    Website: 'AI Tool Tracker',
    URL: 'https://www.aitooltracker.com/',
    Price: 'Free',
    Tag: '',
  },
  {
    DA: 28,
    Website: 'AI Tool Shed',
    URL: 'http://aitoolshed.ai/',
    Price: 'Free',
    Tag: '',
  },
  {
    DA: 28,
    Website: 'Share Tool List',
    URL: 'https://www.sharetoollist.com/',
    Price: 'Free',
    Tag: '',
  },
  {
    DA: 25,
    Website: 'AiLibs',
    URL: 'https://ailibs.co/',
    Price: 'Free',
    Tag: '',
  },
  {
    DA: 22,
    Website: 'Insight',
    URL: 'http://insightai.co/',
    Price: 'Free',
    Tag: '',
  },
  {
    DA: 18,
    Website: 'AI powered marketing tools',
    URL: 'https://www.aipoweredmarketingtools.com/',
    Price: '$99.00',
    Tag: 'AI, Business',
  },
  {
    DA: 16,
    Website: 'AI Business Tools',
    URL: 'https://aibusinesstools.com/',
    Price: 'Free',
    Tag: 'Business',
  },
  {
    DA: 14,
    Website: '100AI Tools',
    URL: 'https://100aitools.com/',
    Price: 'Free',
    Tag: 'AI',
  },
  {
    DA: 12,
    Website: 'Better-Made',
    URL: 'http://better-made.io/',
    Price: '$2.50',
    Tag: '',
  },
  {
    DA: 12,
    Website: 'ai.tools',
    URL: 'https://ai.tools/',
    Price: 'Free',
    Tag: 'AI',
  },
  {
    DA: 11,
    Website: 'AItoolsmall.com',
    URL: 'https://aitoolsmall.com/',
    Price: '$0.99',
    Tag: 'AI, Productivity',
  },
  {
    DA: 9,
    Website: 'AiProjectTools',
    URL: 'https://aiprojecttools.com/',
    Price: 'Free',
    Tag: 'AI',
  },
  {
    DA: 7,
    Website: 'AItoolsKit',
    URL: 'https://aitoolskit.com/',
    Price: 'Free',
    Tag: 'AI',
  },
  {
    DA: 5,
    Website: 'AI Finder',
    URL: 'http://aifinder.io/',
    Price: 'Free',
    Tag: 'AI, Business',
  },
  {
    DA: 3,
    Website: 'all things AI',
    URL: 'https://allthingsai.com/',
    Price: 'Free',
    Tag: 'AI',
  },
  {
    DA: 10,
    Website: 'Artiverse AI',
    URL: 'https://artiverse.app/',
    Price: 'Free',
    Tag: 'AI',
  },
];
